/***************************************************************************
 *
 *  Programmers and Purdue Email Addresses:
 *  1. deanp@purdue.edu
 *  2. subbiah@purdue.edu
 *  3. hall529@purdue.edu
 *
 *  Lab 02:
 *
 *  Academic Integrity Statement:
 *
 *  We have not used source code obtained from any other unauthorized source,
 *  either modified or unmodified.  Neither have we provided access to our code
 *  to another. The effort we are submitting is our own original work.
 *
 *  Jan 11th, 3:30, SC G073:
 *
 *  Program Description:
 *  The program takes the charge of 3 point charges and calculates the resultant
 *  force on the point charge at the origin.
 *
 ***************************************************************************/
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#define pi 3.14159265 // Defining constant pi

/***************************************************************************
*
*  Function Information
*
*  Name of Function:
*  Electric Field by Point Charge Calculator
*
*  Function Return Type:
*  double
*  
*  Parameters (list data type, name, and comment one per line):
*    1. double ptCharge (point charge coulombs)
*    2. double r (distance r from reference point)
*
*  Function Description:
*  This function takes a point charge value in coulombs and its distance from
*  its reference point and returns the electric field generated by the point
*  charge at that point.
*
***************************************************************************/
double eField(double ptCharge, double r)
{
  double k = 8.99 * pow(10,9); // Defining k as 8.99e9
  double eFieldMag; // Magnitude of electric field
  double rHat = -r/r; // Calculating rHat
  eFieldMag = k * ((ptCharge)/(pow(r,2))) * rHat;
  return eFieldMag;
}

/***************************************************************************
*
*  Function Information
*
*  Name of Function:
*  2D Vector Magnitude Calculator
*
*  Function Return Type:
*  double  
*
*  Parameters (list data type, name, and comment one per line):
*    1. double vec[2] (vector of size 2 to have x and y coords)
*
*  Function Description:
*  This function calculates the magnitude of a vector with x and y coords.
*
***************************************************************************/
double mag(double vec[2])
{
  double mag;
  mag = sqrt((pow(vec[0], 2)) + (pow(vec[1], 2)));
  return mag;
}

/***************************************************************************
*
*  Function Information
*
*  Name of Function:
*  Vector Angle Calculator
*
*  Function Return Type:
*  double
*
*  Parameters (list data type, name, and comment one per line):
*    1. double vec[2] (double vector of size 2 to have x and y coords)
*
*  Function Description:
*  This function returns the angle between a vector with x and y coords.
*
***************************************************************************/
double angle(double vec[2])
{
  double angle;
  angle = (atan(vec[1]/vec[0]) * 180) / pi; // Finding the angle of vector by x-axis
  return angle;
}

int main (void)
{
  double charge1; // Coulombic charge of charge 1 (micro C)
  double charge2; // Coulombic charge of charge 2 (micro C)
  double charge3; // Coulombic charge of charge 3 (micro C)
  double y; // y value of charge 3 (cm)
  double x; // x value of charge 3 (cm)
  double fNetVec[2]; // Net force vector (N)
  double fNetMag; // Magnitude of the net force (N)
  double fNetAngle; // Angle of the net force degrees
  double eC2OnC1; // Electric field of charge 2 on 1 (N/C)
  double eC3OnC1; // Electric field of charge 3 on 1 (N/C)
  double fC2OnC1; // Force of charge 2 on 1 (N)
  double fC3OnC1; // Force of charge 3 on 1 (N)

  // Recieving input from user for charges 
  printf("Enter charge [micro-Coulomb] of point #1 -> ");
  scanf("%lf", &charge1);
  printf("Enter charge [micro-Coulomb] of point #2 -> ");
  scanf("%lf", &charge2);
  printf("Enter charge [micro-Coulomb] of point #3 -> ");
  scanf("%lf", &charge3);
  // Recieving input for y and x coordinates of charge 2 and 3
  printf("Enter Y coordinate [cm] of point #2 -> ");
  scanf("%lf", &y);
  printf("Enter X coordinate [cm] of point #3 -> ");
  scanf("%lf", &x);
  printf("\n");

  // Converting micro coulombs to coulombs
  charge1 *= pow(10, -6);
  charge2 *= pow(10, -6);
  charge3 *= pow(10, -6);

  // Converting cm to m
  y *= pow(10, -2);
  x *= pow(10, -2);

  // Calculating electric fields and forces from charge 2 and 3
  eC2OnC1 = eField(charge2, y);
  eC3OnC1 = eField(charge3, x);
  fC2OnC1 = eC2OnC1 * charge1;
  fC3OnC1 = eC3OnC1 * charge1;
  // Finding net force vector and its magnitude and angle
  fNetVec[0] = fC3OnC1;
  fNetVec[1] = fC2OnC1;
  fNetMag = mag(fNetVec);
  fNetAngle = angle(fNetVec);

  // Outputing net force magnitude and angle with the x-axis
  printf("Magnitude of the resultant force on the charge at the origin: %.1f N\n", fNetMag);
  printf("Force vector angle with the x-axis: %.1f degrees\n", fNetAngle);
}
